version: "3.5"
services:
  myapp:
    build:
      context: .
    container_name: gosample-app
    environment:
      MYSQL_HOST: myappdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: gosample
    ports:
      - "8080:8080"
    depends_on:
      - myappdb
  myappdb:
    image: mysql:5.7
    container_name: gosample
    environment:
      MYSQL_DATABASE: gosample
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
